let state={events:[],memoryHistory:[],requestHistory:[],resources:[]};
const $=id=>document.getElementById(id); const fmtBytes=n=>{if(!n&&n!==0)return'—';let u=['B','KB','MB','GB','TB'],i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
async function api(url,opt={}){let r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});return r.json()}
function tabs(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='resources')renderResources()})}tabs();
function draw(canvas,data,label){if(!canvas)return;let dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;let c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);c.strokeStyle='#203553';c.lineWidth=1;for(let i=0;i<5;i++){let y=20+i*(h-45)/4;c.beginPath();c.moveTo(35,y);c.lineTo(w-10,y);c.stroke()}if(data.length<2)return;let max=Math.max(...data,1),min=Math.min(...data,0),range=max-min||1;c.strokeStyle='#38d7ff';c.lineWidth=3;c.beginPath();data.forEach((v,i)=>{let x=35+i*(w-50)/(data.length-1),y=h-25-(v-min)/range*(h-55);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.fillStyle='#91a7c0';c.font='11px system-ui';c.fillText(label||'',38,14);c.fillText(String(Math.round(max)),5,25);c.fillText(String(Math.round(min)),5,h-25)}
function renderWorkers(target='workersMini'){let ws=state.metrics?.worker_states||[];$(target).innerHTML=ws.map(w=>`<div class="worker"><b>W${w.id}</b><span class="badge ${w.alive?(w.busy?'warn':'good'):'bad'}" style="float:right">${w.alive?(w.busy?'BUSY':'IDLE'):'FAILED'}</span><div class="muted" style="margin-top:12px">Requests: ${w.requests}</div></div>`).join('')||'<div class="muted">No workers reported.</div>'}
function renderEvents(){let ev=state.events.slice(-100).reverse();$('eventsList').innerHTML=ev.map(e=>`<div class="event"><span>${e.timestamp||''}</span><span class="ev">${e.event||''}</span><span>${e.detail||''}</span></div>`).join('')||'<p class="muted">No events yet.</p>'}
function renderResources(){let q=($('resourceSearch')?.value||'').toLowerCase();$('resourceGrid').innerHTML=state.resources.filter(r=>JSON.stringify(r).toLowerCase().includes(q)).map(r=>`<article class="resource"><span class="badge good">${r.category}</span><h3>${r.title}</h3><p class="muted">${r.description||''}</p><small>${r.filename} · ${fmtBytes(r.size)}</small><div class="actions"><a class="btn" href="http://127.0.0.1:9090/resource/${encodeURIComponent(r.filename)}" target="_blank">View</a><button class="btn" onclick='editResource(${JSON.stringify(r.id)})'>Edit</button><button class="btn danger" onclick='deleteResource(${JSON.stringify(r.id)})'>Delete</button></div></article>`).join('')||'<p class="muted">No resources.</p>'}
async function refresh(){let s=await api('/api/status');state={...state,...s,metrics:s.metrics};let m=s.metrics||{};$('serverState').textContent=m.server_running?'SERVER RUNNING':'SERVER STOPPED';$('dot').style.background=m.server_running?'#56e39f':'#ff6b7a';$('mReq').textContent=m.requests_total||0;$('mQueue').textContent=(m.queue_size||0)+' / '+(m.queue_capacity||0);$('mActive').textContent=m.active_connections||0;let hit=m.cache_hits||0,miss=m.cache_misses||0;$('mCache').textContent=(hit+miss?((hit/(hit+miss))*100).toFixed(1):'0')+'%';$('workerCount').textContent=m.workers||0;$('qCap').textContent=m.queue_capacity||0;$('bytes').textContent=fmtBytes(m.bytes_sent||0);$('failed').textContent=m.requests_failed||0;let mem=s.memory||{};let pct=mem.used_percent||0;$('memPct').textContent=pct.toFixed(1)+'%';$('memBig').textContent=pct.toFixed(1)+'%';$('memBar').style.width=pct+'%';$('memText').textContent=`Used ${fmtBytes(mem.used)} of ${fmtBytes(mem.total)} · Available ${fmtBytes(mem.available)}`;$('memDetailed').textContent=`Total ${fmtBytes(mem.total)} · Available ${fmtBytes(mem.available)} · Used ${fmtBytes(mem.used)} · Free ${fmtBytes(mem.free)}`;['mtotal','mavailable','mused','mfree','mbuf','mcache'].forEach((id,i)=>$(id).textContent=fmtBytes([mem.total,mem.available,mem.used,mem.free,mem.buffers,mem.cached][i]));state.memoryHistory.push(pct);if(state.memoryHistory.length>60)state.memoryHistory.shift();state.requestHistory.push(m.requests_total||0);if(state.requestHistory.length>60)state.requestHistory.shift();draw($('memChart'),state.memoryHistory,'Used memory %');draw($('memChart2'),state.memoryHistory,'Used memory %');draw($('reqChart'),state.requestHistory,'Total requests');renderWorkers();renderWorkers('workersFull');renderEvents();renderResources();}
async function startServer(){await api('/api/start',{method:'POST',body:JSON.stringify({workers:8})});setTimeout(refresh,500)}async function stopServer(){await api('/api/stop',{method:'POST',body:'{}'});setTimeout(refresh,700)}
function newResource(){ $('resourceForm').classList.remove('hidden');$('formTitle').textContent='Add Resource';['rid','rtitle','rcat','rdesc','rfile'].forEach(x=>$(x).value='');$('rupload').value=''}function closeForm(){$('resourceForm').classList.add('hidden')}
async function saveResource(){let file=$('rupload').files[0],data={title:$('rtitle').value,category:$('rcat').value,description:$('rdesc').value,filename:$('rfile').value};if(file){data.filename=file.name;const bytes=new Uint8Array(await file.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=0x8000){bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000))}data.content=btoa(bin);data.base64=true}else if(!data.filename)data.filename='resource.txt';let id=$('rid').value;await api(id?'/api/resources/'+id:'/api/resources',{method:id?'PUT':'POST',body:JSON.stringify(data)});closeForm();await refresh()}
function editResource(id){let r=state.resources.find(x=>x.id===id);if(!r)return;$('resourceForm').classList.remove('hidden');$('formTitle').textContent='Edit Resource';$('rid').value=r.id;$('rtitle').value=r.title;$('rcat').value=r.category;$('rdesc').value=r.description||'';$('rfile').value=r.filename;$('rupload').value=''}
async function deleteResource(id){if(!confirm('Delete this resource and its file?'))return;await api('/api/resources/'+id,{method:'DELETE',body:'{}'});refresh()}
async function fault(){let r=await api('/api/fault',{method:'POST',body:'{}'});$('faultResult').textContent=r.message||'Fault requested. Watch the event timeline and workers.';setTimeout(refresh,500)}
async function runPerf(){let workers=+$('perfWorkers').value,requests=+$('perfRequests').value;await api('/api/start',{method:'POST',body:JSON.stringify({workers})});$('perfResult').textContent='Running benchmark…';let r=await api('/api/performance',{method:'POST',body:JSON.stringify({workers,requests})});$('perfResult').innerHTML=`<b>${r.requests_per_second.toFixed(1)} requests/sec</b><br>Success: ${r.success} · Errors: ${r.errors} · Elapsed: ${r.elapsed.toFixed(3)} s`;refresh()}
setInterval(refresh,1000);refresh();
